apiVersion: v2
name: fluxy
description: A Helm chart for deploying fluxy to kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
    - name: redis
      version: 18.5.0
      repository: https://charts.bitnami.com/bitnami
    - name: postgresql
      version: 13.2.24
      repository: https://charts.bitnami.com/bitnami
