replicaCount: 1
postgresql:
    auth:
        postgresPassword: "123"
        username: "karan"
        password: "123"
        database: "fluxy"

redis:
    redis:
        password: ""

image:
    repository: fluxy
    tag: latest
    pullPolicy: IfNotPresent

service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

server:
    algorithm: rolling-window
    debug: true
    port: 8000
    host: 0.0.0.0
