version: "3.8"

services:
    postgres:
        container_name: fluxy_db
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always
        networks:
            - fluxy_network

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        logging:
            driver: none
        volumes:
            - pgadmin_data:/var/lib/pgadmin

    redis:
        container_name: fluxy_redis
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - redis_data:/data
        networks:
            - fluxy_network

    fluxy:
        container_name: fluxy_server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - postgres
        links:
            - postgres:postgres
        volumes:
            - .:/app
        restart: always
        networks:
            - fluxy_network

volumes:
    postgres_data:
    pgadmin_data:
    redis_data:

networks:
    fluxy_network:
        driver: bridge
