apiVersion: v1
kind: ConfigMap
metadata:
  name: fluxy-cm
  labels:
    app: fluxy
data:
  ALGORITHM: {{ .Values.server.algorithm }}
  DEBUG: "{{ .Values.server.debug }}"
  SERVER_HOST: {{ .Values.server.host }}
  SERVER_PORT: "{{ .Values.server.port }}"