apiVersion: v1
kind: Secret
metadata:
  name: fluxy-secret
  labels:
    app: fluxy
type: Opaque
data:
    DB_NAME: {{ .Values.postgresql.auth.database | b64enc | quote }}
    DB_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
    DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
    DB_HOST: {{ "fluxy-postgresql" | b64enc | quote }}
    DB_PORT: {{ "5432" | b64enc }}
    DB_LOG_MODE: {{ "True" | b64enc }}
    SSL_MODE: {{ "disable" | b64enc | quote }}

    REDIS_HOST: {{ "fluxy-redis-master" | b64enc | quote }} 
    REDIS_PORT: {{ "6379" | b64enc }}
    REDIS_PASSWORD: {{ .Values.redis.redis.password | b64enc | quote }}